/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as iamDataDaoSol from "./IAMDataDao.sol";
export type { iamDataDaoSol };
import type * as institutionDaoSol from "./InstitutionDao.sol";
export type { institutionDaoSol };
import type * as interface from "./interface";
export type { interface };
export type { DaoManager } from "./DaoManager";
