/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as iamDataDaoSol from "./IAMDataDao.sol";
export * as institutionDaoSol from "./InstitutionDao.sol";
export * as interface from "./interface";
export { DaoManager__factory } from "./DaoManager__factory";
